### ISSUE TITLE
Uncaught Type Error at line 3017

### ISSUE THREAD

**Issue by sangemaru** [TSTPrep/sfwd-lms#1]
https://github.com/TSTPrep/sfwd-lms/blob/a7736e6dfefb1f5c683595b7174437963dd012d3/includes/lib/wp-pro-quiz/js/wpProQuiz_front.min.js#L2988C1-L3031C1

@valentinceaprazaru 

https://tstprep.com/topic/vocabulary-questions-2/
https://tstprep.com/app/plugins/sfwd-lms/includes/lib/wp-pro-quiz/js/wpProQuiz_front.min.js?ver=4.7.0 
`Uncaught TypeError: essayText is undefined`
`line 3017`

**Comment by valentinceaprazaru** [comment]
fixed by v4.7.0.6-patch
